// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	challenges "CrudPlatform/internal/core/domain/repository/model/challenges"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	repository "CrudPlatform/internal/core/domain/repository"
)

// CommunicationChallengeServices is an autogenerated mock type for the CommunicationChallengeServices type
type CommunicationChallengeServices struct {
	mock.Mock
}

// CreateChallenge provides a mock function with given fields: ctx, request
func (_m *CommunicationChallengeServices) CreateChallenge(ctx *gin.Context, request *challenges.Challenge) (*repository.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateChallenge")
	}

	var r0 *repository.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.Challenge) (*repository.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.Challenge) *repository.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *challenges.Challenge) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteChallenge provides a mock function with given fields: ctx, request
func (_m *CommunicationChallengeServices) DeleteChallenge(ctx *gin.Context, request *challenges.DeleteChallenge) (*repository.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChallenge")
	}

	var r0 *repository.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.DeleteChallenge) (*repository.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.DeleteChallenge) *repository.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *challenges.DeleteChallenge) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectChallenge provides a mock function with given fields: ctx, request
func (_m *CommunicationChallengeServices) SelectChallenge(ctx *gin.Context, request *challenges.GetChallenge) (*repository.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SelectChallenge")
	}

	var r0 *repository.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.GetChallenge) (*repository.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.GetChallenge) *repository.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *challenges.GetChallenge) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChallenge provides a mock function with given fields: ctx, request
func (_m *CommunicationChallengeServices) UpdateChallenge(ctx *gin.Context, request *challenges.UpdateChallenge) (*repository.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChallenge")
	}

	var r0 *repository.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.UpdateChallenge) (*repository.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *challenges.UpdateChallenge) *repository.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *challenges.UpdateChallenge) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommunicationChallengeServices creates a new instance of CommunicationChallengeServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommunicationChallengeServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommunicationChallengeServices {
	mock := &CommunicationChallengeServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
