// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	schemavideos "CrudPlatform/internal/core/domain/repository/schema/videos"

	videos "CrudPlatform/internal/core/domain/repository/model/videos"
)

// DBRepositoryVideo is an autogenerated mock type for the DBRepositoryVideo type
type DBRepositoryVideo struct {
	mock.Mock
}

// CreateVideo provides a mock function with given fields: ctx, request
func (_m *DBRepositoryVideo) CreateVideo(ctx *gin.Context, request *videos.Videos) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateVideo")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.Videos) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.Videos) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *videos.Videos) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteVideo provides a mock function with given fields: ctx, request
func (_m *DBRepositoryVideo) DeleteVideo(ctx *gin.Context, request *videos.DeleteVideo) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.DeleteVideo) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectVideo provides a mock function with given fields: ctx, request
func (_m *DBRepositoryVideo) SelectVideo(ctx *gin.Context, request *videos.GetVideo) (*schemavideos.VideosGetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SelectVideo")
	}

	var r0 *schemavideos.VideosGetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.GetVideo) (*schemavideos.VideosGetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.GetVideo) *schemavideos.VideosGetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemavideos.VideosGetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *videos.GetVideo) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVideo provides a mock function with given fields: ctx, request
func (_m *DBRepositoryVideo) UpdateVideo(ctx *gin.Context, request *videos.UpdateVideo) (*schemavideos.VideosUpdateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVideo")
	}

	var r0 *schemavideos.VideosUpdateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.UpdateVideo) (*schemavideos.VideosUpdateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *videos.UpdateVideo) *schemavideos.VideosUpdateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemavideos.VideosUpdateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *videos.UpdateVideo) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDBRepositoryVideo creates a new instance of DBRepositoryVideo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBRepositoryVideo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBRepositoryVideo {
	mock := &DBRepositoryVideo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
